using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Http.Internal;
using Microsoft.Extensions.Primitives;
using System;
using System.Collections.Generic;
using System.Text;
using System.Threading.Tasks;

namespace IdentityServer.Infrastructure.Mailing
{
    /// <summary>
    /// Helper to generate the link for password reset
    /// </summary>
    public static class ResetPasswordLinkGenerator
    {
        /// <summary>
        /// Generate link method
        /// </summary>
        /// <param name="userName">user name</param>
        /// <param name="token">token generated by aspnet identity</param>
        /// <param name="baseUrl">identity server Url</param>
        /// <param name="path">Path to reset password action</param>
        /// <returns></returns>
        public static string Generate(string userName, string token, string baseUrl, string path)
        {
            var queryParams = GenerateResetPasswordQueryParams(token, userName).FormatQueryString();

            var link = $"{baseUrl}{path}?{queryParams}";

            return link;
        }

        private static IQueryCollection GenerateResetPasswordQueryParams(string token, string username)
        {
            var queryParams = new QueryCollection(
                new Dictionary<string, StringValues>()
                {
                    {"token", token },
                    {"username", username }
                });
            return queryParams;
        }
    }
}
